export const columns = [
  {
    title: '',
    type: 'selection',
    width: '50px',
    fixed: 'left',
  },
  {
    title: '#',
    type: 'index',
    width: '50px',
    fixed: 'left',
  },
  {
    key: 'bizType',
    title: '业务类型',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'bucket',
    title: '桶',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'storageType',
    title: '存储策略',
    hide: true,
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'path',
    title: '文件路径',
    minWidth: '100px',
    showOverflowTooltip: true,
    align: 'left',
    customSlot: 'path',
  },
  {
    key: 'uniqueFileName',
    title: '文件名称',
    minWidth: '100px',
    showOverflowTooltip: true,
    align: 'left',
  },
  {
    key: 'fileType',
    title: '文件类型',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'contentType',
    title: '内容类型',
    hide: true,
    align: 'center',
  },
  {
    key: 'suffix',
    title: '后缀',
    hide: true,
    width: '80px',
    align: 'center',
  },
  {
    key: 'size',
    title: '文件大小',
    sortable: 'custom',
    align: 'center',
    customSlot: 'size',
  },
  {
    key: 'createTime',
    title: '上传时间',
    sortable: 'custom',
    width: '180px',
    align: 'center',
  },
  {
    key: 'operator',
    title: '操作',
    width: '80px',
    align: 'center',
    customSlot: 'operator',
    fixed: 'right',
  },
]
