export const columns = [
  // {
  //   title: '',
  //   type: 'selection',
  //   width: '50px',
  //   fixed: 'left',
  // },
  {
    title: '#',
    type: 'index',
    width: '50px',
    fixed: 'left',
  },
  {
    key: 'state',
    title: '状态',
    sortable: 'custom',
    align: 'center',
    width: '140px',
    customSlot: 'state',
  },
  {
    key: 'account',
    title: '账号',
    align: 'center',
    width: '140px',
  },
  {
    key: 'createTime',
    title: '登录时间',
    align: 'center',
    sortable: 'custom',
    width: '180px',
  },
  {
    key: 'comments',
    title: '备注',
    minWidth: '200px',
  },
  {
    key: 'os',
    title: '操作系统',
    width: '120px',
    align: 'center',
  },
  {
    key: 'device',
    title: '设备名称',
    align: 'center',
    width: '400px',
    showOverflowTooltip: true,
  },
  {
    key: 'browser',
    title: '浏览器类型',
    align: 'center',
    minWidht: '120px',
  },
  {
    key: 'ip',
    title: 'ip地址',
    align: 'center',
    minWidht: '120px',
  },
]
