export const columns = [
  {
    title: '',
    type: 'selection',
    width: '50px',
    fixed: 'left',
  },
  {
    title: '#',
    type: 'index',
    width: '50px',
    fixed: 'left',
  },
  {
    key: 'avatar',
    title: '头像',
    width: '80px',
    align: 'center',
    hide: true,
    customSlot: 'avatar',
  },
  {
    key: 'username',
    title: '用户名',
    align: 'center',
    minWidth: '100px',
    showOverflowTooltip: true,
  },
  {
    key: 'account',
    title: '账号',
    align: 'center',
    minWidth: '100px',
    showOverflowTooltip: true,
  },
  {
    key: 'roles',
    title: '角色',
    align: 'center',
    customSlot: 'roles',
    minWidth: '100px',
    showOverflowTooltip: true,
  },
  {
    key: 'sex',
    title: '性别',
    sortable: 'custom',
    align: 'center',
    width: '100px',
    customSlot: 'sex',
  },
  {
    key: 'email',
    title: '邮箱',
    align: 'center',
    minWidth: '100px',
    showOverflowTooltip: true,
  },
  {
    key: 'mobile',
    title: '手机号',
    align: 'center',
    minWidth: '100px',
    showOverflowTooltip: true,
  },
  {
    key: 'birthday',
    title: '生日',
    hide: true,
    width: '160px',
    align: 'center',
    minWidth: '100px',
    showOverflowTooltip: true,
  },
  {
    key: 'state',
    title: '状态',
    sortable: 'custom',
    width: '120px',
    align: 'center',
    customSlot: 'state',
  },
  {
    key: 'createTime',
    title: '注册时间',
    width: '180px',
    sortable: 'custom',
    align: 'center',
  },
  {
    key: 'operator',
    title: '操作',
    align: 'center',
    width: '180px',
    customSlot: 'operator',
    fixed: 'right',
  },
]
